version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    command: yarn start -p ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    stdin_open: true
    tty: true
